# Generated by Django 4.2.7 on 2024-01-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('mailing', '0005_rename_user_message_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='day',
            field=models.IntegerField(blank=True, help_text='Введите число при периодичности раз в месяц. Число должно быть от 1 до 31', null=True, verbose_name='день'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='day_week',
            field=models.CharField(blank=True, choices=[(1, 'понедельник'), (2, 'вторник'), (3, 'среда'), (4, 'четверг'), (5, 'пятница'), (6, 'суббота'), (7, 'воскресенье')], help_text='Выберите день недели при периодичности раз в неделю', max_length=15, null=True, verbose_name='день недели'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='clients',
            field=models.ManyToManyField(blank=True, null=True, to='client.client', verbose_name='клиенты рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='periodicity',
            field=models.CharField(blank=True, choices=[(1, 'Раз в день'), (2, 'Раз в неделю'), (3, 'Раз в месяц')], default=1, max_length=50, null=True, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время начала рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[(1, 'Создана'), (2, 'Запущена'), (3, 'Завершена')], default=1, max_length=50, verbose_name='статус рассылки'),
        ),
    ]
