# Generated by Django 4.2.7 on 2024-01-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_remove_mailing_day_remove_mailing_day_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='periodicity',
            field=models.CharField(blank=True, choices=[(1, 'Раз в день'), (2, 'Раз в неделю'), (3, 'Раз в месяц')], max_length=50, null=True, verbose_name='периодичность'),
        ),
    ]
