# Generated by Django 4.2.7 on 2024-02-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_alter_mailing_periodicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='активность рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='periodicity',
            field=models.CharField(blank=True, choices=[('1', 'Раз в день'), ('2', 'Раз в неделю'), ('3', 'Раз в месяц')], max_length=50, null=True, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('1', 'Создана'), ('2', 'Запущена'), ('3', 'Завершена')], default=1, max_length=50, verbose_name='статус рассылки'),
        ),
    ]
