# Generated by Django 4.2.7 on 2024-02-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_user'),
        ('mailing', '0009_mailing_is_active_alter_mailing_periodicity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='clients',
            field=models.ManyToManyField(to='client.client', verbose_name='клиенты рассылки'),
        ),
    ]
