# Generated by Django 4.2.7 on 2024-02-03 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0010_alter_mailing_clients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='owner',
            new_name='user',
        ),
    ]
