# Generated by Django 4.2.7 on 2024-01-29 15:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-time_try'], 'verbose_name': 'Лог', 'verbose_name_plural': 'Логи'},
        ),
        migrations.RenameField(
            model_name='log',
            old_name='mailing_list',
            new_name='mailing_current',
        ),
        migrations.RemoveField(
            model_name='log',
            name='time',
        ),
        migrations.AddField(
            model_name='log',
            name='time_try',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='дата и время попытки'),
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='log',
            name='client',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='клиент'),
        ),
        migrations.AlterField(
            model_name='log',
            name='server_response',
            field=models.TextField(blank=True, null=True, verbose_name='ответ почтового сервера'),
        ),
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(choices=[('1', 'Успешно'), ('0', 'Неуспешно')], max_length=20, verbose_name='статус попытки'),
        ),
    ]
